SELECT * FROM MOVIES;
SELECT ID FROM MOVIES;
SELECT TITLE FROM MOVIES;
SELECT DIRECTOR FROM MOVIES;
SELECT YEAR FROM MOVIES;
SELECT LENGH_MINUTES FROM MOVIES;

day 2
sql WHERE, AND, OR ,BETWEEN

SELECT * FROM MOVIES WHERE ID BETWEEN 1 AND 6;
SELECT TITLE, YEAR, ID FROM MOVIES
WHERE YEAR BETWEEN 1990 AND 2000;
SELECT ID FROM MOVIES WHERE ID=1;
SELECT title, director, year FROM movies
WHERE Director = ("John Lasseter" or director =  "Brad Bird" 
and year between 2000 and 2011);
